// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import { default as handler } from "./.open-next/worker.js";

const EMAIL_PROCESS_PATH = "/api/internal/email-deliveries/process";

export default {
  fetch: handler.fetch,

  async scheduled(
    _event: { cron: string; scheduledTime: number },
    env: {
      WORKER_SELF_REFERENCE: { fetch: (request: Request) => Promise<Response> };
      EMAIL_WORKER_SECRET: string;
    },
  ) {
    const response = await env.WORKER_SELF_REFERENCE.fetch(
      new Request(
        "https://expodia-flight" + EMAIL_PROCESS_PATH,
        {
          method: "POST",
          headers: {
            "x-email-worker-secret": env.EMAIL_WORKER_SECRET,
          },
        },
      ),
    );

    if (!response.ok) {
      throw new Error(`Email delivery worker returned ${response.status}`);
    }
  },
};