'use client';

import { FormEvent, useEffect, useState } from 'react';
import { createSupabaseBrowserClient } from '@/lib/supabase/client';
import { AdminShell } from '@/components/admin/AdminShell';

type Code={id:string;intended_email:string|null;expires_at:string|null;revoked_at:string|null;max_redemptions:number;redemption_count:number;created_at:string};
type Provider={id:string;name:string;category:string;website_url:string|null;booking_url:string|null;api_status:string;account_status:string;company_account_email:string|null;referral_enabled:boolean};
type Task={id:string;provider_id:string;task_type:string;status:string;requires_human:boolean;created_at:string};
type App={user_id:string;short_message:string;created_at:string;agents:{display_name:string;email:string}|null};

export default function AdminPage(){
 const supabase=createSupabaseBrowserClient();
 const [codes,setCodes]=useState<Code[]>([]),[providers,setProviders]=useState<Provider[]>([]),[tasks,setTasks]=useState<Task[]>([]),[applications,setApplications]=useState<App[]>([]);
 const [email,setEmail]=useState(''),[partnerEmail,setPartnerEmail]=useState(''),[days,setDays]=useState('30'),[max,setMax]=useState('1'),[newCode,setNewCode]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 async function load(){const [{data:c},{data:p},{data:t},{data:a}]=await Promise.all([
  supabase.from('agent_registration_codes').select('id,intended_email,expires_at,revoked_at,max_redemptions,redemption_count,created_at').order('created_at',{ascending:false}),
  supabase.from('marketplace_providers').select('id,name,category,website_url,booking_url,api_status,account_status,company_account_email,referral_enabled').order('name'),
  supabase.from('partner_onboarding_tasks').select('id,provider_id,task_type,status,requires_human,created_at').order('created_at',{ascending:false}).limit(100),
  supabase.from('agent_applications').select('user_id,short_message,created_at,agents(display_name,email)').order('created_at',{ascending:false})
 ]);setCodes((c||[]) as Code[]);const {data:setting}=await supabase.from('management_settings').select('value').eq('key','partner_account_email').maybeSingle();setPartnerEmail(setting?.value||'');setProviders((p||[]) as Provider[]);setTasks((t||[]) as Task[]);setApplications((a||[]) as unknown as App[]);setLoading(false);}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 async function issue(e:FormEvent){e.preventDefault();setMessage('');setNewCode('');const expiry=new Date(Date.now()+Number(days)*86400000).toISOString();const {data,error}=await supabase.rpc('create_agent_referral_code',{p_intended_email:email.trim()||null,p_expires_at:expiry,p_max_redemptions:Number(max)});if(error||!data?.[0]){setMessage(error?.message||'Could not issue referral code.');return}setNewCode(data[0].referral_code);setEmail('');void load();}
 async function revoke(id:string){const {error}=await supabase.from('agent_registration_codes').update({revoked_at:new Date().toISOString()}).eq('id',id);setMessage(error?'Could not revoke code.':'Referral code revoked.');void load();}
 async function savePartnerEmail(){const {error}=await supabase.from('management_settings').upsert({key:'partner_account_email',value:partnerEmail.trim()||null,updated_at:new Date().toISOString()},{onConflict:'key'});setMessage(error?'Could not save company partner email.':'Company partner email saved.');}
 async function createTask(provider:Provider,taskType:string){const {error}=await supabase.from('partner_onboarding_tasks').insert({provider_id:provider.id,task_type:taskType,status:'QUEUED',requires_human:true,company_account_email:partnerEmail.trim()||provider.company_account_email,notes:'AI working group prepares the workflow; human authorization is required for third-party terms, email verification, credentials and account ownership.'});setMessage(error?'Could not create onboarding task.':'Onboarding task created.');void load();}
 async function signOut(){await supabase.auth.signOut();window.location.assign('/access');}
 return <AdminShell><main className="verificationPage"><section className="verificationCard" style={{maxWidth:1180,width:'min(96vw,1180px)'}}>
 <div className="verificationBadge">EXPODIA MANAGEMENT</div><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center'}}><div><h1 style={{marginTop:12}}>Management dashboard</h1><p>Professional access, marketplace partners, onboarding and support operations.</p></div><button className="publicSecondary" onClick={signOut}>Log out</button></div>
 <section style={{marginTop:28}}><h2>Company partner account</h2><p>Use the company-controlled mailbox for provider applications and verification codes. The system records the address for onboarding tasks; it does not bypass provider verification.</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><input type="email" value={partnerEmail} onChange={e=>setPartnerEmail(e.target.value)} placeholder="company partner email"/><button className="publicPrimary" onClick={savePartnerEmail}>Save</button></div></section><section style={{marginTop:28}}><h2>Professional invitations</h2><form onSubmit={issue} style={{display:'grid',gap:12,gridTemplateColumns:'2fr 1fr 1fr auto',alignItems:'end'}}><label>Invited email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Optional"/></label><label>Valid for<select value={days} onChange={e=>setDays(e.target.value)}><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label><label>Uses<select value={max} onChange={e=>setMax(e.target.value)}><option>1</option><option>5</option><option>10</option></select></label><button className="primary">Generate</button></form>{newCode&&<div className="notice" style={{marginTop:16}}><strong>{newCode}</strong><br/>Give this six-digit code only to the invited professional.</div>}{message&&<div className="notice" role="status" style={{marginTop:12}}>{message}</div>}</section>
 <section style={{marginTop:36}}><h2>Partner marketplace</h2><p>Providers are registered with their source, imagery, booking path, connection state and onboarding requirements. No provider is treated as connected merely because it is listed.</p>{loading?<p>Loading…</p>:<div style={{display:'grid',gap:12}}>{providers.map(p=><article key={p.id} className="notice"><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong>{p.name}</strong><br/><small>{p.category} · API {p.api_status} · Account {p.account_status} · Referral {p.referral_enabled?'enabled':'not configured'}</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{p.website_url&&<a className="publicSecondary" href={p.website_url} target="_blank" rel="noreferrer">Source</a>}<button className="publicSecondary" onClick={()=>createTask(p,'RESEARCH')}>Research</button><button className="publicSecondary" onClick={()=>createTask(p,'ACCOUNT_CREATE')}>Prepare account</button></div></div></article>)}</div>}</section>
 <section style={{marginTop:36}}><h2>AI working group / partner onboarding</h2><p>The system can research providers, prepare applications, track onboarding and tell management what is waiting. Third-party account creation, email verification, legal acceptance and credential issuance remain explicit company-authorized steps.</p><div style={{display:'grid',gap:8}}>{tasks.map(t=><div className="notice" key={t.id}><strong>{t.task_type}</strong> · {providers.find(p=>p.id===t.provider_id)?.name||'Provider'} · {t.status}{t.requires_human?' · Human action required':''}</div>)}{!tasks.length&&<p>No onboarding tasks yet.</p>}</div></section>
 <section style={{marginTop:36}}><h2>Referral codes</h2>{codes.length===0?<p>No referral codes issued.</p>:<div style={{overflowX:'auto'}}><table><thead><tr><th>Invited email</th><th>Expires</th><th>Uses</th><th>Status</th><th/></tr></thead><tbody>{codes.map(c=><tr key={c.id}><td>{c.intended_email||'Any invited email'}</td><td>{c.expires_at?new Date(c.expires_at).toLocaleString():'No expiry'}</td><td>{c.redemption_count}/{c.max_redemptions}</td><td>{c.revoked_at?'Revoked':c.expires_at&&new Date(c.expires_at)<=new Date()?'Expired':'Active'}</td><td>{!c.revoked_at&&<button className="publicSecondary" onClick={()=>revoke(c.id)}>Revoke</button>}</td></tr>)}</tbody></table></div>}</section>
 <section style={{marginTop:36}}><h2>Professional applications</h2>{applications.length===0?<p>No applications yet.</p>:applications.map(a=><article className="notice" key={a.user_id}><strong>{a.agents?.display_name||'Applicant'}</strong> · {a.agents?.email}<p>{a.short_message}</p><small>{new Date(a.created_at).toLocaleString()}</small></article>)}</section>
 </section></main></AdminShell>
}